version: '3'
services:
  frontend:
    build: ./cha  # Docker will look for Dockerfile in this directory
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./cha/src:/app/frontend/src
      - ./cha/index.html:/app/frontend/index.html
    working_dir: /app/frontend